-- Baseline core schema that existed before the tracked migration history.
-- Kept idempotent so new Supabase projects can replay the full history while
-- existing projects are not disturbed.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  bio text,
  user_code integer generated by default as identity unique,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;

drop policy if exists "Profiles are viewable by everyone" on public.profiles;
create policy "Profiles are viewable by everyone"
on public.profiles
for select
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  kp_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'open'
    check (status in ('open', 'closed', 'archived', 'completed')),
  room_number integer generated by default as identity unique,
  password text
);

alter table public.rooms enable row level security;

drop policy if exists "Rooms are viewable by everyone" on public.rooms;
create policy "Rooms are viewable by everyone"
on public.rooms
for select
using (true);

drop policy if exists "Authenticated users can create rooms" on public.rooms;
create policy "Authenticated users can create rooms"
on public.rooms
for insert
to authenticated
with check (auth.uid() = kp_id);

drop policy if exists "KP can update rooms" on public.rooms;
create policy "KP can update rooms"
on public.rooms
for update
using (auth.uid() = kp_id);

drop policy if exists "KP can delete rooms" on public.rooms;
create policy "KP can delete rooms"
on public.rooms
for delete
using (auth.uid() = kp_id);

create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  user_id uuid references auth.users(id) on delete cascade,
  room_id uuid references public.rooms(id) on delete set null,
  name text not null,
  type text not null default 'investigator'
    check (type in ('investigator', 'npc', 'monster')),
  role text,
  info jsonb not null default '{}'::jsonb,
  stats jsonb not null default '{}'::jsonb,
  theme_color text,
  inventory text
);

alter table public.characters enable row level security;

drop policy if exists "Characters are viewable by room participants" on public.characters;
create policy "Characters are viewable by room participants"
on public.characters
for select
to authenticated
using (
  user_id = auth.uid()
  or room_id is null
  or exists (
    select 1
    from public.rooms room
    where room.id = characters.room_id
      and room.kp_id = auth.uid()
  )
  or exists (
    select 1
    from public.characters own_character
    where own_character.room_id = characters.room_id
      and own_character.user_id = auth.uid()
  )
);

drop policy if exists "Users can create characters" on public.characters;
create policy "Users can create characters"
on public.characters
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Owner or KP can update characters" on public.characters;
create policy "Owner or KP can update characters"
on public.characters
for update
using (
  auth.uid() = user_id
  or auth.uid() in (
    select room.kp_id
    from public.rooms room
    where room.id = characters.room_id
  )
)
with check (
  auth.uid() = user_id
  or auth.uid() in (
    select room.kp_id
    from public.rooms room
    where room.id = characters.room_id
  )
  or room_id is null
);

drop policy if exists "Owner or KP can delete characters" on public.characters;
create policy "Owner or KP can delete characters"
on public.characters
for delete
using (
  auth.uid() = user_id
  or auth.uid() in (
    select room.kp_id
    from public.rooms room
    where room.id = characters.room_id
  )
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  character_id uuid references public.characters(id) on delete set null,
  recipient_id uuid references auth.users(id) on delete set null,
  type text not null default 'normal'
    check (type in ('normal', 'system', 'status', 'dice', 'dice_secret', 'image')),
  content text not null,
  meta jsonb not null default '{}'::jsonb
);

alter table public.messages enable row level security;

drop policy if exists "Authenticated users can insert messages" on public.messages;
create policy "Authenticated users can insert messages"
on public.messages
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Messages visibility" on public.messages;
create policy "Messages visibility"
on public.messages
for select
to authenticated
using (
  recipient_id is null
  or user_id = auth.uid()
  or recipient_id = auth.uid()
  or auth.uid() in (
    select room.kp_id
    from public.rooms room
    where room.id = messages.room_id
  )
);

drop policy if exists "Users can delete own messages" on public.messages;
create policy "Users can delete own messages"
on public.messages
for delete
using (auth.uid() = user_id);

create index if not exists idx_profiles_created_at
  on public.profiles(created_at);

create index if not exists idx_rooms_kp_id
  on public.rooms(kp_id);

create index if not exists idx_characters_user_id
  on public.characters(user_id);

create index if not exists idx_characters_room_id
  on public.characters(room_id);

create index if not exists idx_messages_room_id
  on public.messages(room_id);

create index if not exists idx_messages_user_id
  on public.messages(user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nickname', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

grant select on public.profiles to anon, authenticated;
grant select on public.rooms to anon, authenticated;
grant select on public.characters to authenticated;
grant select on public.messages to authenticated;

notify pgrst, 'reload schema';
